[package]
name = "dyncast-impl"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.62"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.2"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
