[package]
name = "dyncast"
version = "0.1.0"
description = "Downcasting made easy"
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.62"

[dependencies]
dyncast-impl = { version = "=0.1.0", path = "./impl" }
once_cell = "1.17.1"

[workspace]
members = ["impl"]
