[package]
name = "dyncast"
version = "0.1.0"
description = "Downcasting made easy"
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.74"

[dependencies]
sptr = "0.3.2"

dyncast-impl = { version = "=0.1.0", path = "./impl" }

[workspace]
members = ["impl"]
